---
# Kerberos KDC role - Handlers

- name: restart krb5-kdc
  ansible.builtin.systemd:
    name: krb5-kdc
    state: restarted

- name: restart krb5-admin-server
  ansible.builtin.systemd:
    name: krb5-admin-server
    state: restarted
